name: Build and Release
on:
  push:
    branches:
      - main  # mainブランチが更新された場合
    tags:
      - "v*"  # vで始まるタグがプッシュされた場合

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@main

      - name: Set up Python 3.8
        uses: actions/setup-python@main
        with: { python-version: 3.8 }

      - name: Upgrade pip
        run: python -m pip install -r requirements.txt

      - name: build
        run: pyinstaller -F krAuthenticator.py --onefile --noconsole
  
      - name: upload
        uses: actions/upload-artifact@v1
        with:
          name: krAuthenticator-windows
          path: dist/krAuthenticator.exe

  macOS-build:
    runs-on: macOS-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@main

      - name: Set up Python 3.8
        uses: actions/setup-python@main
        with: { python-version: 3.8 }

      - name: Upgrade pip
        run: python -m pip install -r requirements.txt

      - name: build
        run: pyinstaller -F krAuthenticator.py --onefile --noconsole

      - name: upload
        uses: actions/upload-artifact@v1
        with:
          name: krAuthenticator-macos
          path: dist/krAuthenticator

  ubuntu-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@main

      - name: Set up Python 3.8
        uses: actions/setup-python@main
        with: { python-version: 3.8 }

      - name: Upgrade pip
        run: python -m pip install -r requirements.txt

      - name: build
        run: pyinstaller -F krAuthenticator.py --onefile --noconsole

      - name: upload
        uses: actions/upload-artifact@v1
        with:
          name: krAuthenticator-linux
          path: dist/krAuthenticator

  release:
    needs: [ubuntu-build, macOS-build, windows-build]
    runs-on: ubuntu-latest

    steps:
      - name: Download Linux
        uses: actions/download-artifact@v1
        with:
          name: krAuthenticator-linux

      - name: Download Mac
        uses: actions/download-artifact@v1
        with:
          name: krAuthenticator-macos

      - name: Download Windows
        uses: actions/download-artifact@v1
        with:
          name: krAuthenticator-windows

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'release-${{ github.run_number }}'
          release_name: 'Release-${{ github.run_number }}'
          draft: false
          prerelease: false

      - name: Zip
        run: |
          tar -C krAuthenticator-macos -pczvf krAuthenticator-macos.tar.gz krAuthenticator
          tar -C krAuthenticator-linux -pczvf krAuthenticator-linux.tar.gz krAuthenticator
          zip --junk-paths krAuthenticator-windows ./krAuthenticator-windows/krAuthenticator.exe
      - name: Append Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./krAuthenticator-macos.tar.gz
          asset_name: krAuthenticator-macos.tar.gz
          asset_content_type: application/gzip

      - name: Append Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./krAuthenticator-linux.tar.gz
          asset_name: krAuthenticator-linux.tar.gz
          asset_content_type: application/gzip

      - name: Append Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./krAuthenticator-windows.zip
          asset_name: krAuthenticator-windows.zip
          asset_content_type: application/zip