name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyinstaller

    - name: Build Executable
      run: pyinstaller --onefile krAuthenticator.py

    - name: Rename Executable for Mac
      if: matrix.os == 'macOS-latest'
      run: mv ./dist/krAuthenticator ./dist/krAuthenticator-mac

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # ここでトークンを設定
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ github.sha }}
        draft: false
        prerelease: false

    - name: Upload Executable to Release
      if: matrix.os == 'windows-latest'
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/krAuthenticator.exe
        asset_name: krAuthenticator-windows.exe
        asset_content_type: application/octet-stream

    - name: Upload Executable to Release
      if: matrix.os == 'macOS-latest'
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/krAuthenticator-mac
        asset_name: krAuthenticator-mac
        asset_content_type: application/octet-stream
